require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Therapist' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-speech-to-text', :path => '../node_modules/react-native-google-speech-to-text'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'TherapistTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Therapist-tvOS' do
  # Pods for Therapist-tvOS

  target 'Therapist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
